sudo: required
services:
    - docker

before_install:
   - docker build -t subash/docker-react -f Dockerfile.dev .    
script:
  - docker run -e CI=true subash/docker-react npm run test -- --coverage  